name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create secrets file
        run: |
          echo "RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}" > .kamal/secrets
          echo "KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}" >> .kamal/secrets
          echo "KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}" >> .kamal/secrets
          echo "POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}" >> .kamal/secrets
          echo "DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}" >> .kamal/secrets
          echo "DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}" >> .kamal/secrets
          echo "DISCORD_REDIRECT_URI: ${{ secrets.DISCORD_REDIRECT_URI }}" >> .kamal/secrets
          echo "DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}" >> .kamal/secrets
          echo "DISCORD_SERVER_ID: ${{ secrets.DISCORD_SERVER_ID }}" >> .kamal/secrets
          echo "WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}" >> .kamal/secrets

      - name: Deploy with Kamal
        run: bin/kamal deploy
